# This is a basic workflow to help you get started with Actions

name: workflow with multiple jobs

# Controls when the workflow will run
on:
  schedule:
  - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      GREETING: "Hello"
      NAME: "World"
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: print greeting
        run: echo "${{ env.GREETING }}, ${{ env.NAME }}!"

  reveal-secrets:
    runs-on: ubuntu-latest
    needs: greet
    steps:
    
      - uses: actions/checkout@v4
      - name: print secret
        run: echo "The secret is ${{ secrets.MOCK_API_KEY }}"

      
      

    


